# Porta padrão para o backend de atendimento
server.port=8080

spring.datasource.url=jdbc:postgresql://192.168.122.151:5432/clinica
spring.datasource.username=clinica
spring.datasource.password=clinica
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Kafka (ajustadas para o IP correto da máquina com Kafka)
kafka.url=192.168.122.152:9092

# Nome do tópico Kafka para notificar que o áudio foi recebido
kafka.topico.transcrever=transcrever
kafka.topico.resumir=resumir
kafka.topico.extrair=extrair

# whisper url server
whisper.url=http://192.168.122.153:5001/transcrever

# the DeepSeek inference endpoint
deepseek.url=http://192.168.122.153:11434/api/generate

# redis url server
redis.url=redis://192.168.122.152:6379