
spring.datasource.url=jdbc:postgresql://192.168.122.151:5432/clinica
spring.datasource.username=clinica
spring.datasource.password=clinica
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta padrão para o backend de atendimento
server.port=8080

# Nome do tópico Kafka para notificar que o áudio foi recebido
app.kafka.topico.transcrever=transcrever
app.kafka.topico.resumir=resumir

# Configurações do Kafka (ajustadas para o IP correto da máquina com Kafka)
spring.kafka.bootstrap-servers=192.168.122.152:9092
spring.kafka.consumer.group-id=atendimento-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# the DeepSeek inference endpoint
deepseek.url=http://192.168.122.153:11434/api/generate
