# Porta padrão para o backend de atendimento
server.port=8080

# Configurações de database
spring.datasource.url=jdbc:postgresql://100.64.64.201:5432/clinica
spring.datasource.username=clinica
spring.datasource.password=clinica
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do kafka
kafka.url=100.64.64.202:9092
kafka.topico.transcrever=transcrever
kafka.topico.resumir=resumir
kafka.topico.extrair=extrair

# Configurações do whisper
whisper.url=http://100.64.64.203:5001/transcrever

# Configurações do deepseek
deepseek.url=http://100.64.64.203:11434/api/generate

# Configurações do redis
redis.url=redis://100.64.64.202:6379

# Configurações do deepgram
deepgram.api.url=https://api.deepgram.com/v1/listen
deepgram.api.key=b6ede36ecfafc81f95214ce9a16e694658f1e4a7

#Configurações de transcrição
transcrever.service=deepgram
